### ISSUE TITLE
pkgfile doesn't work with pacman 3.5

### ISSUE THREAD

**Issue by wonder** [Daenyth/pkgtools#28]
<pre>
 sudo pkgfile -u
 :: Converting local repo ...
 Traceback (most recent call last):
   File "/usr/bin/pkgfile", line 434, in <module>
     main()
   File "/usr/bin/pkgfile", line 416, in main
     update_repo(options)
   File "/usr/bin/pkgfile", line 210, in update_repo
     local_dbpath = os.path.join(find_dbpath(), 'local')
   File "/usr/lib/python2.7/posixpath.py", line 68, in join
     elif path == '' or path.endswith('/'):
 AttributeError: 'NoneType' object has no attribute 'endswith'
</pre>

pacman 3.5 has a new database format
